# Site settings
lang: nl
title: Drentse vereniging van ergotherapeuten
tagline: Samen sterker in de zorg
description: >-
  Samenwerkingsverband van ergotherapeuten in Drenthe. 
  Samen sterker in de zorg voor betere ergotherapeutische ondersteuning.

url: "https://ergotherapeindrenthe.netlify.app"
baseurl: ""

# Author (for the sidebar)
author:
  name: Drentse vereniging van ergotherapeuten
  email: info@ergotherapeuten-drenthe.nl
  about: |
    Wij zijn een netwerk van professionele ergotherapeuten 
    verspreid door heel Drenthe, die samen werken aan de 
    beste zorg voor onze cliënten.

# Sidebar navigation
menu:
  - title: Wie zijn wij
    url: /wie-zijn-wij/
  - title: Deelnemers
    url: /deelnemers/
  - title: Waarom ergotherapie
    url: /waarom-ergotherapie/
  - title: Nieuws
    url: /nieuws/
  - title: Contact
    url: /contact/

# Theme settings
accent_image: /assets/img/sidebar-bg.jpg
accent_color: rgb(44,95,93)
theme_color: rgb(44,95,93)

# Collections
collections:
  deelnemers:
    permalink: /deelnemers/:name/
    output: true

# Build settings
theme: jekyll-theme-hydejack
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

kramdown:
  math_engine: mathjax
  footnote_backlink: '&#x21a9;&#xfe0e;'

# Exclude from processing
exclude:
  - README.md
  - CHANGELOG.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor