backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "pages"
    label: "Pagina's"
    files:
      - label: "Wie zijn wij"
        name: "wie-zijn-wij"
        file: "_pages/wie-zijn-wij.md"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Inhoud", name: "body", widget: "markdown"}
      
      - label: "Waarom ergotherapie"
        name: "waarom-ergotherapie"
        file: "_pages/waarom-ergotherapie.md"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Inhoud", name: "body", widget: "markdown"}
      
      - label: "Contact"
        name: "contact"
        file: "_pages/contact.md"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Inhoud", name: "body", widget: "markdown"}

  - name: "deelnemers"
    label: "Deelnemers"
    folder: "_deelnemers"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Bedrijfsnaam", name: "title", widget: "string"}
      - {label: "Logo", name: "logo", widget: "image"}
      - {label: "Website", name: "website", widget: "string"}
      - {label: "Beschrijving", name: "body", widget: "markdown"}
      - {label: "Foto", name: "foto", widget: "image", required: false}

  - name: "nieuws"
    label: "Nieuws"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Datum", name: "date", widget: "datetime"}
      - {label: "Inhoud", name: "body", widget: "markdown"}